# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
a= np.__version__
print(a)
b= np.show_config()
print(b)

1.24.4
openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['openblas\\lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['openblas\\lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['openblas\\lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['openblas\\lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['openblas\\lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['openblas\\lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['openblas\\lib']
    language = c
    define_macros = [('HAVE_CBLAS', None

#### 3. Create a null vector of size 10 (★☆☆)

In [3]:
a=np.zeros(10) #it will create a null vector of length 10
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [4]:
myarr= np.array([1,3,4,5,177])
myarr.dtype



dtype('int32')

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [5]:
a=np.zeros(10)
print(a)
a[5]=1
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [6]:
a=np.arange(10,49)  #array range from 10 to 49 
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [7]:
a=np.array([1,2,3,4,5])
a=a[::-1] #used slicing (-1=[a.len-1])
print(a)

[5 4 3 2 1]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [8]:
myarr= np.array([[0,1,2],[3,4,5],[6,7,8]])
print(myarr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [9]:
a=np.array([1,2,0,0,4,0])
arr=np.where(a!=0)
print(arr)

(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [10]:
arr=np.array([[1,0,0],[0,1,0],[0,0,1]])
print(arr)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [11]:
arr=np.random.random(((3,3,3)))
print(arr)

[[[0.68030171 0.82708008 0.51732592]
  [0.01868882 0.32927398 0.96629099]
  [0.33893547 0.61302736 0.76556456]]

 [[0.49782774 0.89305758 0.10376994]
  [0.61520633 0.61683051 0.07199782]
  [0.0483127  0.39063758 0.46675173]]

 [[0.86005642 0.40871959 0.28316164]
  [0.42817391 0.97993343 0.29114176]
  [0.60855613 0.22359346 0.02716268]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [12]:
arr=np.random.random((10,10))
print(arr)
minimum=arr.min()
maximum=arr.max()
print(minimum,maximum)

[[0.79621974 0.44228817 0.92801767 0.9746525  0.1118622  0.95695822
  0.00682846 0.40839224 0.81281517 0.20943601]
 [0.69594184 0.99776454 0.43735617 0.61212498 0.98370845 0.26738593
  0.04370925 0.09217077 0.85300713 0.57903742]
 [0.97819321 0.57631107 0.20507226 0.80207474 0.6259423  0.04711185
  0.21227282 0.47527684 0.01979451 0.37506552]
 [0.59978618 0.47925434 0.25475207 0.25056043 0.13767527 0.17084782
  0.03933426 0.39352758 0.31909529 0.0737754 ]
 [0.44285934 0.67219928 0.7534707  0.69849469 0.5503235  0.10399603
  0.24776222 0.99855458 0.82933941 0.49337338]
 [0.2918164  0.00290827 0.89652678 0.17777952 0.32953308 0.23784645
  0.43606898 0.6108146  0.55966368 0.68540286]
 [0.94034036 0.18699571 0.37977055 0.00916268 0.74022742 0.01962885
  0.73501219 0.27351234 0.88541473 0.7460158 ]
 [0.10599425 0.71631009 0.92561098 0.97593844 0.2209172  0.79899495
  0.46928886 0.0049555  0.84159674 0.57610888]
 [0.76871188 0.47438503 0.6218055  0.53840829 0.52986011 0.31606053
  0.32080968

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [13]:
arr=np.random.random(30)
print(arr)

print(np.mean(arr))

[0.0499917  0.13879161 0.14469021 0.83098816 0.5886571  0.3416485
 0.9175209  0.87275911 0.86547275 0.4999216  0.39674909 0.78099141
 0.60919665 0.60538863 0.63197122 0.49320219 0.2940383  0.26900811
 0.45134268 0.88654658 0.74206801 0.10312372 0.65494739 0.57659476
 0.98703289 0.36705456 0.86002417 0.53017866 0.55567632 0.60439163]
0.5549989539652714


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [14]:
a=np.ones((3,3)) #it creates a 3*3 matrix with all elements as one
a[1:-1,1:-1]=0   #second element to (len-1)
print(a)

[[1. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [15]:
a=np.zeros((5,5)) #reverse logic of above questuon
a[1:-1,1:-1]=1
print(a)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [16]:
#imp
a = np.zeros((8, 8))
a[1::2, ::2] = 1  #(from index one, select every second row; from index 0,select every  second column)
a[::2, 1::2] = 1  #(from index zero, select every second row; from index 1, select every secodn column)
print(a)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [17]:
print(np.unravel_index(100,(6,7,8)))  #Syntax: unravel_index(index, shape)

(1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [18]:
a=np.random.random((5,5))
print(a)
a=a-a.min()/a.max()-a.min()   #formula to normalize a matrix
print(a)

[[0.13693158 0.42220099 0.49452998 0.7783884  0.25359434]
 [0.67528048 0.80738922 0.95054388 0.87246789 0.9053005 ]
 [0.41355535 0.89871712 0.52401194 0.08710215 0.8652864 ]
 [0.06130692 0.78135113 0.56348743 0.40406212 0.88037704]
 [0.83582452 0.03696076 0.1115351  0.71833553 0.14521908]]
[[ 0.06108703  0.34635643  0.41868542  0.70254384  0.17774978]
 [ 0.59943592  0.73154466  0.87469932  0.79662333  0.82945594]
 [ 0.33771079  0.82287256  0.44816738  0.01125759  0.78944184]
 [-0.01453764  0.70550657  0.48764287  0.32821756  0.80453248]
 [ 0.75997996 -0.0388838   0.03569054  0.64249097  0.06937452]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [19]:
arr1=np.random.random((5,3))
arr2=np.random.random((3,2))
arr=np.dot(arr1,arr2)  #printing product of array1 and array2
print(arr)

[[1.12129967 0.70548197]
 [1.56744005 1.13079096]
 [1.15352919 0.87847531]
 [1.14542843 0.57983304]
 [0.8285972  0.49984205]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [20]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
for i in range(3, 9):
    arr[i] = np.negative(arr[i])

print(arr)


[ 1  2  3 -4 -5 -6 -7 -8 -9 10]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [21]:
#range(5)=0,1,2,3,4
#sum(10,-1)
9
9

9

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

#### 29. How to round away from zero a float array ? (★☆☆)

In [22]:
def rounding(x):
    return np.round(x)
print(rounding(np.array([45.55, 23.52])))

[46. 24.]


#### 30. How to find common values between two arrays? (★☆☆)

In [23]:
arr1=[1,2,3,4,5,6]
arr2=[4,5,6,7,8,9]
print(np.intersect1d(arr1,arr2))    #syntax for finding common values between two arrays

[4 5 6]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [24]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')   #if we use timedelta32, it will give error ," numpy has no syntax timedelta32"
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print( yesterday, today,tomorrow )

2024-07-10 2024-07-11 2024-07-12


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [25]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')  #[D]means days    
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [34]:
a=np.random.uniform((3,3))     #we cannot use np.random.random because it will give a random value between 0 to 1 .
print (np.floor(a))
print (np.ceil(a)-1)

[2. 1.]
[2. 1.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [26]:
a = np.zeros((5,5))
a += np.arange(5)
print(a)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [36]:
def finding():
    for x in range(1,11):
        yield x                                      #yield gives the value and keeps a track of all the values it stores in memory whereas return runs only once and gives the final output
res = np.fromiter(finding(),dtype=float,count=-1)    #numpy.fromiter(iter, dtype, count=-1, *, like=None).Create a new 1-dimensional array from an iterable object.

print(res)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [37]:
#doubt

a=np.random.random(10)
res=np.arange(0,1)
print(res)

[0]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [38]:
a = np.random.random(10)
print(a)
a.sort()
print(a)

[0.36401612 0.68561944 0.26920722 0.7657075  0.77190359 0.60478043
 0.71194173 0.77871961 0.45427533 0.4975416 ]
[0.26920722 0.36401612 0.45427533 0.4975416  0.60478043 0.68561944
 0.71194173 0.7657075  0.77190359 0.77871961]


#### 41. How to sum a small array faster than np.sum? (★★☆)

#### 42. Consider two random array A and B, check if they are equal (★★☆)

#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)